[package]
name = "abi"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.8.8"
alloy-sol-types = "0.8.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.131"
